### PR TITLE
Migrating to hexo-api version 3.x

### PR DESCRIPTION
**Pull request by fentas**
Hi there,
pull request for issue: https://github.com/jaredly/hexo-admin/issues/19

I guess the major change have been that hexo is not anymore reachable globally.
Plus it seems that they splited the hexo package into specific "helper packages".
Hope it helps. : )

Greetings, fentas

P.s.: It runs again, but i didn't test it quite well because i don't know your workflow for bundle.js/css

### CODE REVIEW

**Comment by jaredly** [comment]
Thanks for doing this!

I'll have to look into this more later, though. I'm getting some errors
```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.done (/home/jared/clone/hexo-admin/api.js:74:22)
    at /home/jared/clone/hexo-admin/api.js:157:8
    at /home/jared/clone/hexo-admin/api.js:81:7

```

**Comment by jaredly** [comment]
Now, did you say that it was working completely for you, or just that it loaded without errors?

**Comment by fentas** [comment]
Hey, I tested it a little bit more.
For me there is no errors on server side. (api works well)
But there are problems on client side. If want to edit a post it stucks with "Loading...". (Server response looks fine) Also if I want to create a new post there is absolutely nothing happening. (no request neither).

**Comment by WanielDeiss** [comment]
how is the status with the hexo v3 support? ...

**Comment by NuLL3rr0r** [comment]
Yeah, I would like to know when Hexo v3 support is available, too. By the way, I've already tried it on v2.x and it looks promising.

**Comment by semos** [comment]
There is a pull request for this, you could check out the fork, but i can't
promise anything as i've not tried it.

**Comment by younglaker** [comment]
Has it been merged to the master branch? How about the status with the hexo v3 support?
I tried hexo 3.1.1 and Windows x64, it doesn't work.

**Comment by iGitScor** [comment]
:up:

**Comment by fentas** [comment]
After some time i could finish what i started. Better later then never. : )
Plz validate functionality. For me it seems to work now.
_Honestly I never used the system, so I don't know for what I have to watch out._

If something comes up let me know.

**Comment by jaredly** [comment]
looks pretty good -- I'll test it when I get the chance.
Thanks for helping out!

**Comment by jaredly** [comment]
Awesome! :+1:
The only bug is that you can't set tags / categories :/
```
TypeError: Cannot set property categories of [object Object] which has only a getter
```

**Comment by whzecomjm** [comment]
@fentas how can i use your version in my hexo v3?

**Comment by jaredly** [comment]
but I'll merge it now to unbreak people, and look into fixing it later

**Comment by jaredly** [comment]
@whzecomjm I just published v1.0.0 of hexo-admin, which supports v3.0

**Comment by whzecomjm** [comment]
@jaredly thank you!

**Comment by online** [comment]
@jaredly, hello! How to install the latest version of hexo-admin?

**Comment by whzecomjm** [comment]
@online `npm install hexo-admin --save`

**Comment by whzecomjm** [comment]
@jaredly Hi, It seems ok, but when i check the link "localhost:4000/admin/", I can't see any existing posts (I can see pages)  and there is a error after that.

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.done (E:\lifecho\node_modules\hexo-admin\api.js:74:22)
    at E:\lifecho\node_modules\hexo-admin\api.js:156:8
    at E:\lifecho\node_modules\hexo-admin\api.js:81:7
    at call (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:2
39:7)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
83:5)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at jsonParser (E:\lifecho\node_modules\hexo-admin\node_modules\body-parser\l
ib\types\json.js:100:40)
    at call (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:2
39:7)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
83:5)
    at SendStream.error (E:\lifecho\node_modules\hexo-admin\node_modules\serve-s
tatic\index.js:120:7)
    at SendStream.emit (events.js:107:17)
    at SendStream.error (E:\lifecho\node_modules\hexo-admin\node_modules\serve-s
tatic\node_modules\send\index.js:245:17)
    at SendStream.onStatError (E:\lifecho\node_modules\hexo-admin\node_modules\s
erve-static\node_modules\send\index.js:356:12)
    at next (E:\lifecho\node_modules\hexo-admin\node_modules\serve-static\node_m
odules\send\index.js:630:16)
    at onstat (E:\lifecho\node_modules\hexo-admin\node_modules\serve-static\node
_modules\send\index.js:619:14)
    at FSReqWrap.oncomplete (fs.js:95:15)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.done (E:\lifecho\node_modules\hexo-admin\api.js:74:22)
    at E:\lifecho\node_modules\hexo-admin\api.js:156:8
    at E:\lifecho\node_modules\hexo-admin\api.js:81:7
    at call (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:2
39:7)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
83:5)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at jsonParser (E:\lifecho\node_modules\hexo-admin\node_modules\body-parser\l
ib\types\json.js:100:40)
    at call (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:2
39:7)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
83:5)
    at SendStream.error (E:\lifecho\node_modules\hexo-admin\node_modules\serve-s
tatic\index.js:120:7)
    at SendStream.emit (events.js:107:17)
    at SendStream.error (E:\lifecho\node_modules\hexo-admin\node_modules\serve-s
tatic\node_modules\send\index.js:245:17)
    at SendStream.onStatError (E:\lifecho\node_modules\hexo-admin\node_modules\s
erve-static\node_modules\send\index.js:356:12)
    at next (E:\lifecho\node_modules\hexo-admin\node_modules\serve-static\node_m
odules\send\index.js:630:16)
    at onstat (E:\lifecho\node_modules\hexo-admin\node_modules\serve-static\node
_modules\send\index.js:619:14)
    at FSReqWrap.oncomplete (fs.js:95:15)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.done (E:\lifecho\node_modules\hexo-admin\api.js:74:22)
    at E:\lifecho\node_modules\hexo-admin\api.js:156:8
    at E:\lifecho\node_modules\hexo-admin\api.js:81:7
    at call (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:2
39:7)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
83:5)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
61:14)
    at jsonParser (E:\lifecho\node_modules\hexo-admin\node_modules\body-parser\l
ib\types\json.js:100:40)
    at call (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:2
39:7)
    at next (E:\lifecho\node_modules\hexo-server\node_modules\connect\index.js:1
83:5)
    at SendStream.error (E:\lifecho\node_modules\hexo-admin\node_modules\serve-s
tatic\index.js:120:7)
    at SendStream.emit (events.js:107:17)
    at SendStream.error (E:\lifecho\node_modules\hexo-admin\node_modules\serve-s
tatic\node_modules\send\index.js:245:17)
    at SendStream.onStatError (E:\lifecho\node_modules\hexo-admin\node_modules\s
erve-static\node_modules\send\index.js:356:12)
    at next (E:\lifecho\node_modules\hexo-admin\node_modules\serve-static\node_m
odules\send\index.js:630:16)
    at onstat (E:\lifecho\node_modules\hexo-admin\node_modules\serve-static\node
_modules\send\index.js:619:14)
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by fentas** [comment]
Anyone had the chance to test if the new pull request resolves all issues?

**Comment by jaredly** [comment]
@whzecomjm I just merged @fentas' PR, which should fix these issues

**Comment by sebastienvg** [comment]
Just found and install this plugin works fine, no issue so far.

**Comment by whzecomjm** [comment]
@jaredly oh, thank u.

**Comment by online** [comment]
@jaredly, how can I install the plug-in for testing?

**Comment by fentas** [comment]
@online as described here: https://github.com/jaredly/hexo-admin#quickstart :) all is merged and up to date.

**Comment by online** [comment]
@fentas, Thank you, I understand :wink:

**Pull request merged**
