### PR TITLE
add delete post

### PR DESCRIPTION
**Pull request by dalibormesaric**
screenshot_5
I added X icon next to the settings, and this does what is described in https://github.com/jaredly/hexo-admin/issues/4

### CODE REVIEW

**Comment by dalibormesaric** [comment]
@jaredly any feedback?

**Comment by dalibormesaric** [comment]
ping @jaredly

**Comment by lufeihaidao** [comment]
It seems the author is too busy to maintain this project?

**Comment by xuzaixian** [comment]
you did what i wanted to do,good job

**Comment by jaredly** [comment]
thanks! Sorry for the delay

**Pull request merged**
