### PR TITLE
Add custom post metadata that can be edited from the admin interface

### PR DESCRIPTION
**Pull request by a-ro**

### CODE REVIEW

**Comment by jaredly** [comment]
this looks like a great idea -- could you add some screenshots?

**Comment by PirtleShell** [comment]
I rebased this over the current `master` branch and added this to my config:
```yaml
metadata:
  foo: barDefault!
```

A new post's config dropper looks like this:
image

**Comment by jaredly** [comment]
merged https://github.com/jaredly/hexo-admin/commit/65101bd97aec6c3851237944ef3a825e85469677

**Comment by declan-haojin** [comment]
Hello, I got some problem when adding custom frontmatter `thumbmail` and `toc`, since the value of `toc` is included by `' '` and the value of `thumbmail` has an auto prefix `->`  which causes the custom frontmatter cannot be recognized properly.

The frontmatter of `post.md` generated is below:
```
---
title: Untitled
author: Declan
tags: []
toc: 'true' # I don't need the ' '
password: 
thumbmail: >-
  https://cdn.jsdelivr.net/gh/declan-haojin/blog-image@master/img/20200309093727.png # I don't need the >-
categories: []
date: 2020-04-16 21:38:00
---
```
Thanks.

**Pull request closed without merging**
