### PR TITLE
switched to gulp

### PR DESCRIPTION
**Pull request by dalibormesaric**
Added Gulp for building the application - because windows :+1:

### CODE REVIEW

**Comment by jaredly** [comment]
Cool!
why add all the `/** jsx:**/` pragmas? It was working fine without them...

**Comment by dalibormesaric** [comment]
I get parsing errors without /** @jsx React.DOM */. But I saw here http://stackoverflow.com/questions/20905227/reactjs-unexpected-token-error that the new version of react should not require that.

**Comment by dalibormesaric** [comment]
I'm trying to upgrade react version, and I got to the point where it builds and I have no errors, but the screen in the browser is blank. Any ideas?

**Comment by dalibormesaric** [comment]
Change log
-upgrad react to 0.14.7
-hide link from posts when post is draft

Not working: ( @jaredly can you help? )
-editor
-post/page content styling not the same as before

Things I'm not sure about:
https://github.com/jaredly/hexo-admin/pull/54/files#diff-b9467edd07771e22fed4eb07304fe9b0R32
https://github.com/jaredly/hexo-admin/pull/54/files#diff-8d4a8af8b3771dbcd332b0a873d54b04R8

**Comment by jaredly** [comment]
hmmm this is getting to be a pretty big change. I know it's a pain, but could you remove the places where you add semicolons? it makes it really hard to review the diff & see what actually changed

**Comment by jaredly** [comment]
also, it would be best to split this out into two PRs -- one for gulp, and one for upgrating to the lastest react version

**Comment by dalibormesaric** [comment]
I'm not sure what is the best way of handling this, because this is all related. Gulp wouldn't build without `/** @jsx React.DOM */` (maybe now it would since I changed some libraries from the initial commit), and going forward I think React upgrade is something sooner or later should happen.

I'm not going to argue semicolons because this is your project so if you really insist (again decide what is best going forward).

I'll make this PR just about Gulp upgrade, and let's go from there.

**Comment by dalibormesaric** [comment]
The gulp tooling for building the application has moved on, and I can't track back the versions of the libraries that worked with the current code base.

**Comment by jaredly** [comment]
hmmm yeah. tell you what I'll see if I can get gulp working

**Comment by jaredly** [comment]
ok so this looks like it's working! https://github.com/jaredly/hexo-admin/commit/78d473b062c7e4cf67a863b40cf06c99b80fdb79 could you try it out and make sure it works on your setup?

**Comment by dalibormesaric** [comment]
works! just change package.json "scripts" from make to gulp

what is the next step? I really just wanted to add some features but then all this happened :)

**Comment by jaredly** [comment]
:) yeah
the "delete post" thing is probably most requested, and after that I don't
have much on the roadmap at the moment. I blog way too infrequently to
really know what features would be awesome >.< although I keep telling
myself I'll change that

**Pull request closed without merging**
