### PR TITLE
Fix auth paths

### PR DESCRIPTION
**Pull request by adrianveracom**
If "root" param in hexo config has to end with a "/" this is a fix for that in the auth component.

_Note: I'm still not sure 100% of that assumption but can't find any other documentation that mentions anything against it._

### CODE REVIEW

**Comment by jaredly** [comment]
Actually, could you change these to use `path.join()`? Then it would be robust to a root with or without a trailing `/`.
(or maybe [url-join](https://www.npmjs.com/package/url-join) so that it will work on windows)

**Comment by adrianveracom** [comment]
Cool, that's something we can use across the project too, there is a bunch of other places that we are just using + to join them

**Comment by adrianveracom** [comment]
Switched to url-join!

**Comment by jaredly** [comment]
Awesome! Also, what happens if no `hexo.config.root` is defined? Does it default to `/`? b/c if not (if it defaults to null or something) then we'd need to account for it

**Pull request closed without merging**
