### PR TITLE
Add the deploy page

### PR DESCRIPTION
**Pull request by bobchennan**
use the path specified in yml:
admin:
  path: "/home/ubuntu/workspace/deploy.sh"

the script takes the first parameter as the commit log

### CODE REVIEW

**Comment by jaredly** [comment]
Cool! Can't wait to try it

**Comment by jaredly** [comment]
Thanks for putting this together! I made some changes before merging it in to make it align with the style/organization of the project generally.
For reference (in case you are interested), the changes are:

- put the `deploy` serverside logic in `api.js` along with the other endpoints, splitting out the non-app specific stuff into a separate function
- changed the `path` config value to be `deployCommand` (a bit more specific)
- put the front-end ajax stuff into the `./client/api/rest.js` file w/ the other api helpers, which cuts out a lot of the boilerplate and removes the need for jquery
- changed the react code to use `<input onChanged...` instead of digging into refs (see the [todo example](http://facebook.github.io/react/) on the react homepage for another example of using `<input/>`)
- added an `error` parameter to the `deploy` endpoint to report server errors, etc.
- various ui changes
- standardized code style/indents/etc.

**Comment by bobchennan** [comment]
Wonderful! Let me try it. 
This is my first time to use React. 
Not familiar with that.

**Comment by bobchennan** [comment]
Deploy works fine.
Image dragging isn't working correctly here.

**Comment by jaredly** [comment]
Yeah I don't have dragging implemented -- just "copy + paste". Drag + drop
would be awesome

**Pull request merged**
