### PR TITLE
Native `hexo deploy` and `hexo generate` support from the admin. 

### PR DESCRIPTION
**Pull request by adrianveracom**
After reviewing the way the deploy was implemented I wanted to have support for native hexo commands like deploy and generate, and also keep the support for custom generate and deploy commands

- Added generateCommand (now we have generateCommand and deployCommand under admin in _config.yml)
- If generateCommand is not defined will run `hexo generate` 
- If deployCommand is not defined will run `hexo deploy` 
- Modify interface for deploy

screenshot 2015-12-24 10 11 43

_UI is not that pretty yet. Would love to have more CSS work there but didn't want to make the PR longer and focus on the subject_

### CODE REVIEW

**Comment by jaredly** [comment]
for UI changes like this could you include a screenshot? thanks!

**Comment by adrianveracom** [comment]
Updated PR with a few more changes and a screenshot!

**Comment by jaredly** [comment]
sorry I didn't notice this update -- I like the UI -- do you still want to get this merged in?

**Comment by adrianveracom** [comment]
Nah, that's ok! No worries

**Pull request closed without merging**
